name: Docker Image CI

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [webtrees_update]


jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Build fpm-8.0
      run: | 
        docker build php-fpm-8.0 -f php-fpm-8.0/Dockerfile \
        --tag ghcr.io/$GITHUB_ACTOR/webtrees:fpm-8.0 \
        --tag ghcr.io/$GITHUB_ACTOR/webtrees:latest

    - name: Build fpm-7.4
      run: | 
        docker build php-fpm-7.4 -f php-fpm-7.4/Dockerfile \
        --tag ghcr.io/$GITHUB_ACTOR/webtrees:fpm-7.4

    - name: Docker login
      run: >-
        echo "${{ secrets.GITHUB_TOKEN }}"
        | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
      
    - name: Push image to GitHub
      run: |
        docker push ghcr.io/$GITHUB_ACTOR/webtrees:fpm-8.0
        docker push ghcr.io/$GITHUB_ACTOR/webtrees:latest
        docker push ghcr.io/$GITHUB_ACTOR/webtrees:fpm-7.4
