name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@v2

    - name: Build
      run: | 
        docker build php-fpm-8.0 -f php-fpm-8.0/Dockerfile \
        --tag ghcr.io/$GITHUB_ACTOR/webtrees_docker:fpm-8.0 \
        --tag ghcr.io/$GITHUB_ACTOR/webtrees_docker:latest \
        .
    - name: Docker login
      run: >-
        echo "${{ secrets.GITHUB_TOKEN }}"
        | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
      
    - name: Push image to GitHub
      run: |
        docker push ghcr.io/$GITHUB_ACTOR/webtrees_docker:fpm-8.0
        docker push ghcr.io/$GITHUB_ACTOR/webtrees_docker:latest
